---
- hosts: localhost
  remote_user: root
  vars_files:
    - ../defaults/main.yml
    - ../vars/main.yml

  tasks:
    - include: '../tasks/main.yml'

    - name: Verify the version of virtualenv we want is installed
      shell: /usr/bin/test "$({{ virtualenv_path }}/bin/virtualenv --version 2> /dev/null)" = {{ virtualenv_version }}
