---

- name: virtualenv | Checking installed version of virtualenv
  shell: /usr/bin/test "$({{ virtualenv_path }}/bin/virtualenv --version 2> /dev/null)" = {{ virtualenv_version }}
  register: wanted_version_installed
  ignore_errors: True
  changed_when: "wanted_version_installed.rc == 1"

- name: virtualenv | Fetching virtualenv source
  action: get_url url={{ base_url }}{{ virtualenv_tarball }} dest=/tmp/
  when: wanted_version_installed.rc == 1

# Check GPG signature
- action: get_url url={{ base_url }}{{ virtualenv_tarball }}.asc dest=/tmp/
- command: gpg --keyserver pgp.mit.edu --recv-keys 3372DCFA
- name: virtualenv | Check GPG signature
  command: gpg --verify /tmp/{{ virtualenv_tarball }}.asc /tmp/{{ virtualenv_tarball }}
  when: wanted_version_installed.rc == 1

- name: virtualenv | Unpack virtualenv tarball
  command: tar zxf {{ virtualenv_tarball }} chdir=/tmp
  when: wanted_version_installed.rc == 1

- name: virtualenv | Install
  command: /usr/bin/python setup.py install --prefix={{ virtualenv_path }} chdir=/tmp/{{ virtualenv_prefix }}
  when: wanted_version_installed.rc == 1
