---

- name: virtualenv | Checking installed version of virtualenv
  shell: /usr/bin/test "$({{ virtualenv_path }}/bin/virtualenv --version 2> /dev/null)" = {{ virtualenv_version }}
  register: wanted_version_installed
  ignore_errors: True
  changed_when: "wanted_version_installed.rc == 1"

- include: install.yml
  when: wanted_version_installed.rc == 1
